# Generated by Django 5.0.3 on 2024-03-15 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('total_emp', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=70)),
                ('salary', models.PositiveIntegerField()),
                ('date_of_joining', models.DateField()),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeapp.company')),
            ],
        ),
    ]
